### ISSUE TITLE
[TODO] Front-end changes 

### ISSUE THREAD

**Issue by Lloyd26** [DLSU-CCAPDEV/2223T3-S12-G10#13]
Here are some changes that are yet to be implemented before working for Phase 2 (back-end).
**Note**: Tasks that are marked with an asterisk (*) can be done during the development for Phase 2 and does not necessarily need to delay the project.

- [x] * Add light/dark mode toggle switch, Replace notifications/alerts button to light/dark mode toggle switch
- [x] Fix layout of sign-up page
- [ ] Make profile posts/comments switcher to tabs instead of separate pages
- [x] Add profile settings page

**Comment by Lloyd26** [comment]
✅  "Add profile settings page" task marked as done through commit e5cea3f.
